/*
生成されたこのファイルは、
この管理グローバルクラスの実際のソースコードではありません。
この参照のみのファイルには、クラスのグローバルコンストラクタ、
メソッド、変数、プロパティが表示されます。
コードをコンパイルできるようにするには、すべてのメソッドで null を返します。
*/
global class MarketoAnalyzerController {
    global MarketoAnalyzerController() {

    }
    @RemoteAction
    global static String checkReportAccess(String reportType, String objType, String objId) {
        return null;
    }
    @RemoteAction
    global static Account getAccount(String accountName) {
        return null;
    }
    @RemoteAction
    global static List<Opportunity> getAccountOpportunities(String accountName) {
        return null;
    }
    @RemoteAction
    global static List<String> getAccountVisibleObjectIds(String accountName) {
        return null;
    }
}
